[package]
name = "rgis-automation"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy_jobs = { workspace = true }
bytes = { workspace = true }
crs-definitions = { workspace = true }
geo = { workspace = true }
geo-features = { path = "../geo-features" }
geo-file-loader = { path = "../geo-file-loader" }
geo-raster = { path = "../geo-raster" }
rgis-camera = { path = "../rgis-camera" }
rgis-crs = { path = "../rgis-crs" }
rgis-events = { path = "../rgis-events" }
rgis-layers = { path = "../rgis-layers" }
rgis-primitives = { path = "../rgis-primitives" }
rgis-renderer = { path = "../rgis-renderer" }
rgis-ui = { path = "../rgis-ui" }
rgis-ui-messages = { path = "../rgis-ui-messages" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rgis-file-loader = { path = "../rgis-file-loader" }
rgis-transform = { path = "../rgis-transform" }
rgis-units = { path = "../rgis-units" }
